[project]
authors = ["Ted Neward <ted@tedneward.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "NWCPP"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


[dependencies]
max = ">=25.4.0.dev2025050305,<26"
