[workspace]
authors = ["Ted Neward <ted@tedneward.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "NWCPP"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025071705,<26"
python = ">=3.13.5,<3.14"
